In [1]:
import pandas as pd
import html5lib
from datetime import date
from datetime import datetime
from datetime import timedelta

# Scraping

In [2]:
url = "https://docs.google.com/spreadsheets/d/1Ggtt-LQQ6hZkC8BVvsLf4fQK6GG0D1HPcJ_o0mbmOUk/htmlembed/sheet?headers=false&gid=0"

In [179]:
url2 = 'https://docs.google.com/spreadsheets/d/1s78ushTWYpA0sJyI48XBJ5cwp__1UVWeVuPnCyKZ1FY/htmlembed/sheet?headers=false&gid=0'

In [180]:
all_tables = pd.read_html(url2)

In [182]:
df = pd.DataFrame(all_tables[0])

# Formatting and cleaning

In [183]:
df

,0,1,2,3,4,5,6,7,8,9,10
0,1,NaN,WEDNESDAY NIGHT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,NaN,VOLLEYBALL FIXTURE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,2017-2018 SUMER SEASONâ€¦ UPDATED: 15/01/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,DIVISION ONE,DIVISION TWO,DIVISION THREE,DIVISION FOUR,NaN,NaN,NaN,NaN,NaN,NaN
5,6,1.1 NAH NII,2.1 BBH,3.1 THAT'S WHAT SHE SET!,4.1 ABOVE THE NET (G),NaN,NaN,NaN,NaN,NaN,NaN
6,7,1.2 MIKASA,2.2 THE OAKS,3.2 CHUCKS,4.2 STUNLOCKED,NaN,NaN,NaN,NaN,NaN,NaN
7,8,1.3 DIG IT,2.3 BULA,3.3 PENDING...,4.3 INDECISIVE,NaN,NaN,NaN,NaN,NaN,NaN
8,9,1.4 COSSACKS,2.4 KARASUNO CROWS,3.4 YEEEEET,4.5 SETTO SIX,NaN,NaN,NaN,NaN,NaN,NaN
9,10,1.5 ASMARA,2.5 MAZENOD,3.5 GOTGOT,4.6 ROLLING THUNDER,NaN,NaN,NaN,NaN,NaN,NaN
10,11,1.6 THE PICKLE JAR,2.6 DDPS,3.6 NEW TEAM,4.7 FLYING PANDAS,NaN,NaN,NaN,NaN,NaN,NaN
11,12,1.7 ACES MELBOURNE,2.7 ABOVE THE NET (B),3.7 DIG AND BALLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,NaN,DATE & TIME,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,NaN,17-Jan,6:45,3.1 VS 3.3,Bojan,2.1 VS 2.5,Tommy,4.1 VS 4.7,David,NaN
16,17,NaN,NaN,7:45,1.1 VS 1.5,??,2.2 VS 2.7,??,3.2 VS 3.7,Nelson,NaN
17,18,NaN,NaN,8:45,1.3 VS 1.4,Bojan,2.6 VS 2.4,Tommy,4.5 VS 4.3,David,NaN
18,19,NaN,NaN,9:45,1.6 VS 1.7,Bojan,4.2 VS 4.6,Tommy,3.6 VS 3.5,David,NaN
19,20,NaN,NaN,NaN,BYE: 1.2,NaN,BYE: 2.3,NaN,BYE: 3.4,NaN,NaN
20,21,NaN,24-Jan,6:45,1.7 VS 1.4,Bojan,1.6 VS 1.2,Tommy,2.7 VS 2.5,David,NaN
21,22,NaN,NaN,7:45,2.2 VS 2.3,Bojan,2.6 VS 2.1,Tommy,4.1 VS 4.6,David,NaN
22,23,NaN,NaN,8:45,1.1 VS 1.3,Bojan,4.2 VS 4.3,Tommy,4.7 VS 4.5,David,NaN
23,24,NaN,NaN,9:45,3.4 VS 3.7,Bojan,3.1 VS 3.6,Tommy,3.2 VS 3.5,David,NaN
24,25,NaN,NaN,NaN,BYE: 1.5,NaN,BYE: 2.4,NaN,BYE: 3.3,NaN,NaN
25,26,NaN,31-Jan,6:45,2.1 VS 2.7,Bojan,2.3 VS 2.5,Tommy,2.2 VS 2.4,David,NaN
26,27,NaN,NaN,7:45,1.2 VS 1.4,Bojan,3.2 VS 3.6,Tommy,3.4 VS 3.5,David,NaN
27,28,NaN,NaN,8:45,1.5 VS 1.6,Julian,4.6 VS 4.3,Jenny,4.1 VS 4.5,Mike,NaN
28,29,NaN,NaN,9:45,1.3 VS 1.7,Bojan,3.3 VS 3.7,Tommy,4.2 VS 4.7,David,NaN
29,30,NaN,NaN,NaN,BYE: 1.1,NaN,BYE: 2.6,NaN,BYE: 3.1,NaN,NaN
30,31,NaN,7-Feb,6:45,1.2 VS 1.3,Bojan,2.4 VS 2.5,Tommy,4.7 VS 4.6,David,NaN
31,32,NaN,NaN,7:45,3.3 VS 3.5,Bojan,2.3 VS 2.7,Tommy,3.6 VS 3.4,David,NaN
32,33,NaN,NaN,8:45,1.1 VS 1.7,Bojan,4.2 VS 4.5,Tommy,4.1VS 4.3,David,NaN
33,34,NaN,NaN,9:45,1.5 VS 1.4,Julian,2.6 VS 2.2,Jenny,3.2 VS 3.1,Mike,NaN
34,35,NaN,NaN,NaN,BYE: 1.6,NaN,BYE: 2.1,NaN,BYE: 3.7,NaN,NaN
35,36,NaN,14-Feb,6:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,37,NaN,NaN,7:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,38,NaN,NaN,8:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39,NaN,NaN,9:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,40,NaN,NaN,NaN,BYE: 1.4,NaN,BYE: 2.2,NaN,BYE: 3.5,NaN,NaN
40,41,NaN,21-Feb,6:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,42,NaN,NaN,7:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,43,NaN,NaN,8:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,44,NaN,NaN,9:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,45,NaN,NaN,NaN,BYE: 1.3,NaN,BYE: 2.5,NaN,BYE: 3.6,NaN,NaN
45,46,NaN,28-Feb,6:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,47,NaN,NaN,7:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,48,NaN,NaN,8:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,49,NaN,NaN,9:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,NaN,NaN,NaN,BYE: 1.7,NaN,BYE: 2.7,NaN,BYE: 3.2,NaN,NaN
50,51,NaN,7-Mar,NaN,TBA,NaN,TBA,NaN,TBA,NaN,NaN
51,52,NaN,SEMI,NaN,TBA,NaN,TBA,NaN,TBA,NaN,NaN
52,53,NaN,FINALS,NaN,TBA,NaN,TBA,NaN,TBA,NaN,NaN
53,54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,55,NaN,14-Mar,NaN,TBA,NaN,TBA,NaN,TBA,NaN,NaN
55,56,NaN,GRAND,NaN,TBA,NaN,TBA,NaN,TBA,NaN,NaN
56,57,NaN,FINALS,NaN,TBA,NaN,TBA,NaN,TBA,NaN,NaN
57,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [188]:
df.drop(len(df.columns)-1,axis=1,inplace=True)
df.drop(0,axis=1,inplace=True)

In [190]:
df

,1,2,3,4,5,6,7,8,9
0,NaN,WEDNESDAY NIGHT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,VOLLEYBALL FIXTURE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2017-2018 SUMER SEASONâ€¦ UPDATED: 15/01/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DIVISION ONE,DIVISION TWO,DIVISION THREE,DIVISION FOUR,NaN,NaN,NaN,NaN,NaN
5,1.1 NAH NII,2.1 BBH,3.1 THAT'S WHAT SHE SET!,4.1 ABOVE THE NET (G),NaN,NaN,NaN,NaN,NaN
6,1.2 MIKASA,2.2 THE OAKS,3.2 CHUCKS,4.2 STUNLOCKED,NaN,NaN,NaN,NaN,NaN
7,1.3 DIG IT,2.3 BULA,3.3 PENDING...,4.3 INDECISIVE,NaN,NaN,NaN,NaN,NaN
8,1.4 COSSACKS,2.4 KARASUNO CROWS,3.4 YEEEEET,4.5 SETTO SIX,NaN,NaN,NaN,NaN,NaN
9,1.5 ASMARA,2.5 MAZENOD,3.5 GOTGOT,4.6 ROLLING THUNDER,NaN,NaN,NaN,NaN,NaN
10,1.6 THE PICKLE JAR,2.6 DDPS,3.6 NEW TEAM,4.7 FLYING PANDAS,NaN,NaN,NaN,NaN,NaN
11,1.7 ACES MELBOURNE,2.7 ABOVE THE NET (B),3.7 DIG AND BALLS,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,DATE & TIME,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,17-Jan,6:45,3.1 VS 3.3,Bojan,2.1 VS 2.5,Tommy,4.1 VS 4.7,David
16,NaN,NaN,7:45,1.1 VS 1.5,??,2.2 VS 2.7,??,3.2 VS 3.7,Nelson
17,NaN,NaN,8:45,1.3 VS 1.4,Bojan,2.6 VS 2.4,Tommy,4.5 VS 4.3,David
18,NaN,NaN,9:45,1.6 VS 1.7,Bojan,4.2 VS 4.6,Tommy,3.6 VS 3.5,David
19,NaN,NaN,NaN,BYE: 1.2,NaN,BYE: 2.3,NaN,BYE: 3.4,NaN
20,NaN,24-Jan,6:45,1.7 VS 1.4,Bojan,1.6 VS 1.2,Tommy,2.7 VS 2.5,David
21,NaN,NaN,7:45,2.2 VS 2.3,Bojan,2.6 VS 2.1,Tommy,4.1 VS 4.6,David
22,NaN,NaN,8:45,1.1 VS 1.3,Bojan,4.2 VS 4.3,Tommy,4.7 VS 4.5,David
23,NaN,NaN,9:45,3.4 VS 3.7,Bojan,3.1 VS 3.6,Tommy,3.2 VS 3.5,David
24,NaN,NaN,NaN,BYE: 1.5,NaN,BYE: 2.4,NaN,BYE: 3.3,NaN
25,NaN,31-Jan,6:45,2.1 VS 2.7,Bojan,2.3 VS 2.5,Tommy,2.2 VS 2.4,David
26,NaN,NaN,7:45,1.2 VS 1.4,Bojan,3.2 VS 3.6,Tommy,3.4 VS 3.5,David
27,NaN,NaN,8:45,1.5 VS 1.6,Julian,4.6 VS 4.3,Jenny,4.1 VS 4.5,Mike
28,NaN,NaN,9:45,1.3 VS 1.7,Bojan,3.3 VS 3.7,Tommy,4.2 VS 4.7,David
29,NaN,NaN,NaN,BYE: 1.1,NaN,BYE: 2.6,NaN,BYE: 3.1,NaN
30,NaN,7-Feb,6:45,1.2 VS 1.3,Bojan,2.4 VS 2.5,Tommy,4.7 VS 4.6,David
31,NaN,NaN,7:45,3.3 VS 3.5,Bojan,2.3 VS 2.7,Tommy,3.6 VS 3.4,David
32,NaN,NaN,8:45,1.1 VS 1.7,Bojan,4.2 VS 4.5,Tommy,4.1VS 4.3,David
33,NaN,NaN,9:45,1.5 VS 1.4,Julian,2.6 VS 2.2,Jenny,3.2 VS 3.1,Mike
34,NaN,NaN,NaN,BYE: 1.6,NaN,BYE: 2.1,NaN,BYE: 3.7,NaN
35,NaN,14-Feb,6:45,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,7:45,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,8:45,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,9:45,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,BYE: 1.4,NaN,BYE: 2.2,NaN,BYE: 3.5,NaN
40,NaN,21-Feb,6:45,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,7:45,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,8:45,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,9:45,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,BYE: 1.3,NaN,BYE: 2.5,NaN,BYE: 3.6,NaN
45,NaN,28-Feb,6:45,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,7:45,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,8:45,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,9:45,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,BYE: 1.7,NaN,BYE: 2.7,NaN,BYE: 3.2,NaN
50,NaN,7-Mar,NaN,TBA,NaN,TBA,NaN,TBA,NaN
51,NaN,SEMI,NaN,TBA,NaN,TBA,NaN,TBA,NaN
52,NaN,FINALS,NaN,TBA,NaN,TBA,NaN,TBA,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,14-Mar,NaN,TBA,NaN,TBA,NaN,TBA,NaN
55,NaN,GRAND,NaN,TBA,NaN,TBA,NaN,TBA,NaN
56,NaN,FINALS,NaN,TBA,NaN,TBA,NaN,TBA,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [192]:
df.loc[:,2]

0                                   WEDNESDAY NIGHT
1                                VOLLEYBALL FIXTURE
2     2017-2018 SUMER SEASONâ€¦ UPDATED: 15/01/2018
3                                               NaN
4                                      DIVISION TWO
5                                           2.1 BBH
6                                      2.2 THE OAKS
7                                          2.3 BULA
8                                2.4 KARASUNO CROWS
9                                       2.5 MAZENOD
10                                         2.6 DDPS
11                            2.7 ABOVE THE NET (B)
12                                              NaN
13                                              NaN
14                                      DATE & TIME
15                                           17-Jan
16                                              NaN
17                                              NaN
18                                              NaN
19                                              NaN
20                                           24-Jan
21                                              NaN
22                                              NaN
23                                              NaN
24                                              NaN
25                                           31-Jan
26                                              NaN
27                                              NaN
28                                              NaN
29                                              NaN
30                                            7-Feb
31                                              NaN
32                                              NaN
33                                              NaN
34                                              NaN
35                                           14-Feb
36                                              NaN
37                                              NaN
38                                              NaN
39                                              NaN
40                                           21-Feb
41                                              NaN
42                                              NaN
43                                              NaN
44                                              NaN
45                                           28-Feb
46                                              NaN
47                                              NaN
48                                              NaN
49                                              NaN
50                                            7-Mar
51                                             SEMI
52                                           FINALS
53                                              NaN
54                                           14-Mar
55                                            GRAND
56                                           FINALS
57                                              NaN
58                                              NaN
Name: 2, dtype: object

In [193]:
table2 = df[df.loc[:,2] == 'DATE & TIME'].index.tolist()[0]

In [194]:
table2

14

In [195]:
df1 = df.head(n=table2)

In [196]:
df1

,1,2,3,4,5,6,7,8,9
0,NaN,WEDNESDAY NIGHT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,VOLLEYBALL FIXTURE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2017-2018 SUMER SEASONâ€¦ UPDATED: 15/01/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DIVISION ONE,DIVISION TWO,DIVISION THREE,DIVISION FOUR,NaN,NaN,NaN,NaN,NaN
5,1.1 NAH NII,2.1 BBH,3.1 THAT'S WHAT SHE SET!,4.1 ABOVE THE NET (G),NaN,NaN,NaN,NaN,NaN
6,1.2 MIKASA,2.2 THE OAKS,3.2 CHUCKS,4.2 STUNLOCKED,NaN,NaN,NaN,NaN,NaN
7,1.3 DIG IT,2.3 BULA,3.3 PENDING...,4.3 INDECISIVE,NaN,NaN,NaN,NaN,NaN
8,1.4 COSSACKS,2.4 KARASUNO CROWS,3.4 YEEEEET,4.5 SETTO SIX,NaN,NaN,NaN,NaN,NaN
9,1.5 ASMARA,2.5 MAZENOD,3.5 GOTGOT,4.6 ROLLING THUNDER,NaN,NaN,NaN,NaN,NaN
10,1.6 THE PICKLE JAR,2.6 DDPS,3.6 NEW TEAM,4.7 FLYING PANDAS,NaN,NaN,NaN,NaN,NaN
11,1.7 ACES MELBOURNE,2.7 ABOVE THE NET (B),3.7 DIG AND BALLS,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [197]:
df2 = df.loc[table2+1:,]

In [201]:
df2 = df2.T.reset_index(drop=True).T

In [203]:
df2.drop(0,axis=1,inplace=True)

In [205]:
df2.rename(columns={1: 'Date', 2: 'Time',3:'court1',4:'ref1',5:'court2',6:'ref2',7:'court3',8:'ref3'}, inplace=True)

In [206]:
#fills from above 
df2.Date = df2['Date'].fillna(method='ffill')

In [207]:
df2.head()

      Date  Time      court1   ref1      court2   ref2      court3    ref3
15  17-Jan  6:45  3.1 VS 3.3  Bojan  2.1 VS 2.5  Tommy  4.1 VS 4.7   David
16  17-Jan  7:45  1.1 VS 1.5     ??  2.2 VS 2.7     ??  3.2 VS 3.7  Nelson
17  17-Jan  8:45  1.3 VS 1.4  Bojan  2.6 VS 2.4  Tommy  4.5 VS 4.3   David
18  17-Jan  9:45  1.6 VS 1.7  Bojan  4.2 VS 4.6  Tommy  3.6 VS 3.5   David
19  17-Jan   NaN    BYE: 1.2    NaN    BYE: 2.3    NaN    BYE: 3.4     NaN

In [208]:
df2['Date1'] = df2.Date

In [209]:
df2['Date'] = df2['Date'].astype(str) + "-" + str(today.year)

In [210]:
df2

,Date,Time,court1,ref1,court2,ref2,court3,ref3,Date1
15,17-Jan-2018,6:45,3.1 VS 3.3,Bojan,2.1 VS 2.5,Tommy,4.1 VS 4.7,David,17-Jan
16,17-Jan-2018,7:45,1.1 VS 1.5,??,2.2 VS 2.7,??,3.2 VS 3.7,Nelson,17-Jan
17,17-Jan-2018,8:45,1.3 VS 1.4,Bojan,2.6 VS 2.4,Tommy,4.5 VS 4.3,David,17-Jan
18,17-Jan-2018,9:45,1.6 VS 1.7,Bojan,4.2 VS 4.6,Tommy,3.6 VS 3.5,David,17-Jan
19,17-Jan-2018,NaN,BYE: 1.2,NaN,BYE: 2.3,NaN,BYE: 3.4,NaN,17-Jan
20,24-Jan-2018,6:45,1.7 VS 1.4,Bojan,1.6 VS 1.2,Tommy,2.7 VS 2.5,David,24-Jan
21,24-Jan-2018,7:45,2.2 VS 2.3,Bojan,2.6 VS 2.1,Tommy,4.1 VS 4.6,David,24-Jan
22,24-Jan-2018,8:45,1.1 VS 1.3,Bojan,4.2 VS 4.3,Tommy,4.7 VS 4.5,David,24-Jan
23,24-Jan-2018,9:45,3.4 VS 3.7,Bojan,3.1 VS 3.6,Tommy,3.2 VS 3.5,David,24-Jan
24,24-Jan-2018,NaN,BYE: 1.5,NaN,BYE: 2.4,NaN,BYE: 3.3,NaN,24-Jan
25,31-Jan-2018,6:45,2.1 VS 2.7,Bojan,2.3 VS 2.5,Tommy,2.2 VS 2.4,David,31-Jan
26,31-Jan-2018,7:45,1.2 VS 1.4,Bojan,3.2 VS 3.6,Tommy,3.4 VS 3.5,David,31-Jan
27,31-Jan-2018,8:45,1.5 VS 1.6,Julian,4.6 VS 4.3,Jenny,4.1 VS 4.5,Mike,31-Jan
28,31-Jan-2018,9:45,1.3 VS 1.7,Bojan,3.3 VS 3.7,Tommy,4.2 VS 4.7,David,31-Jan
29,31-Jan-2018,NaN,BYE: 1.1,NaN,BYE: 2.6,NaN,BYE: 3.1,NaN,31-Jan
30,7-Feb-2018,6:45,1.2 VS 1.3,Bojan,2.4 VS 2.5,Tommy,4.7 VS 4.6,David,7-Feb
31,7-Feb-2018,7:45,3.3 VS 3.5,Bojan,2.3 VS 2.7,Tommy,3.6 VS 3.4,David,7-Feb
32,7-Feb-2018,8:45,1.1 VS 1.7,Bojan,4.2 VS 4.5,Tommy,4.1VS 4.3,David,7-Feb
33,7-Feb-2018,9:45,1.5 VS 1.4,Julian,2.6 VS 2.2,Jenny,3.2 VS 3.1,Mike,7-Feb
34,7-Feb-2018,NaN,BYE: 1.6,NaN,BYE: 2.1,NaN,BYE: 3.7,NaN,7-Feb
35,14-Feb-2018,6:45,NaN,NaN,NaN,NaN,NaN,NaN,14-Feb
36,14-Feb-2018,7:45,NaN,NaN,NaN,NaN,NaN,NaN,14-Feb
37,14-Feb-2018,8:45,NaN,NaN,NaN,NaN,NaN,NaN,14-Feb
38,14-Feb-2018,9:45,NaN,NaN,NaN,NaN,NaN,NaN,14-Feb
39,14-Feb-2018,NaN,BYE: 1.4,NaN,BYE: 2.2,NaN,BYE: 3.5,NaN,14-Feb
40,21-Feb-2018,6:45,NaN,NaN,NaN,NaN,NaN,NaN,21-Feb
41,21-Feb-2018,7:45,NaN,NaN,NaN,NaN,NaN,NaN,21-Feb
42,21-Feb-2018,8:45,NaN,NaN,NaN,NaN,NaN,NaN,21-Feb
43,21-Feb-2018,9:45,NaN,NaN,NaN,NaN,NaN,NaN,21-Feb
44,21-Feb-2018,NaN,BYE: 1.3,NaN,BYE: 2.5,NaN,BYE: 3.6,NaN,21-Feb
45,28-Feb-2018,6:45,NaN,NaN,NaN,NaN,NaN,NaN,28-Feb
46,28-Feb-2018,7:45,NaN,NaN,NaN,NaN,NaN,NaN,28-Feb
47,28-Feb-2018,8:45,NaN,NaN,NaN,NaN,NaN,NaN,28-Feb
48,28-Feb-2018,9:45,NaN,NaN,NaN,NaN,NaN,NaN,28-Feb
49,28-Feb-2018,NaN,BYE: 1.7,NaN,BYE: 2.7,NaN,BYE: 3.2,NaN,28-Feb
50,7-Mar-2018,NaN,TBA,NaN,TBA,NaN,TBA,NaN,7-Mar
51,SEMI-2018,NaN,TBA,NaN,TBA,NaN,TBA,NaN,SEMI
52,FINALS-2018,NaN,TBA,NaN,TBA,NaN,TBA,NaN,FINALS
53,FINALS-2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FINALS
54,14-Mar-2018,NaN,TBA,NaN,TBA,NaN,TBA,NaN,14-Mar
55,GRAND-2018,NaN,TBA,NaN,TBA,NaN,TBA,NaN,GRAND
56,FINALS-2018,NaN,TBA,NaN,TBA,NaN,TBA,NaN,FINALS
57,FINALS-2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FINALS
58,FINALS-2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FINALS

In [211]:
df2 = df2.reset_index(drop=True)

Data is scaped

# Extracting specific time

In [212]:
df2.Date = pd.to_datetime(df2.Date,format='%d-%b-%Y',errors='coerce')

In [213]:
df2

,Date,Time,court1,ref1,court2,ref2,court3,ref3,Date1
0,2018-01-17,6:45,3.1 VS 3.3,Bojan,2.1 VS 2.5,Tommy,4.1 VS 4.7,David,17-Jan
1,2018-01-17,7:45,1.1 VS 1.5,??,2.2 VS 2.7,??,3.2 VS 3.7,Nelson,17-Jan
2,2018-01-17,8:45,1.3 VS 1.4,Bojan,2.6 VS 2.4,Tommy,4.5 VS 4.3,David,17-Jan
3,2018-01-17,9:45,1.6 VS 1.7,Bojan,4.2 VS 4.6,Tommy,3.6 VS 3.5,David,17-Jan
4,2018-01-17,NaN,BYE: 1.2,NaN,BYE: 2.3,NaN,BYE: 3.4,NaN,17-Jan
5,2018-01-24,6:45,1.7 VS 1.4,Bojan,1.6 VS 1.2,Tommy,2.7 VS 2.5,David,24-Jan
6,2018-01-24,7:45,2.2 VS 2.3,Bojan,2.6 VS 2.1,Tommy,4.1 VS 4.6,David,24-Jan
7,2018-01-24,8:45,1.1 VS 1.3,Bojan,4.2 VS 4.3,Tommy,4.7 VS 4.5,David,24-Jan
8,2018-01-24,9:45,3.4 VS 3.7,Bojan,3.1 VS 3.6,Tommy,3.2 VS 3.5,David,24-Jan
9,2018-01-24,NaN,BYE: 1.5,NaN,BYE: 2.4,NaN,BYE: 3.3,NaN,24-Jan
10,2018-01-31,6:45,2.1 VS 2.7,Bojan,2.3 VS 2.5,Tommy,2.2 VS 2.4,David,31-Jan
11,2018-01-31,7:45,1.2 VS 1.4,Bojan,3.2 VS 3.6,Tommy,3.4 VS 3.5,David,31-Jan
12,2018-01-31,8:45,1.5 VS 1.6,Julian,4.6 VS 4.3,Jenny,4.1 VS 4.5,Mike,31-Jan
13,2018-01-31,9:45,1.3 VS 1.7,Bojan,3.3 VS 3.7,Tommy,4.2 VS 4.7,David,31-Jan
14,2018-01-31,NaN,BYE: 1.1,NaN,BYE: 2.6,NaN,BYE: 3.1,NaN,31-Jan
15,2018-02-07,6:45,1.2 VS 1.3,Bojan,2.4 VS 2.5,Tommy,4.7 VS 4.6,David,7-Feb
16,2018-02-07,7:45,3.3 VS 3.5,Bojan,2.3 VS 2.7,Tommy,3.6 VS 3.4,David,7-Feb
17,2018-02-07,8:45,1.1 VS 1.7,Bojan,4.2 VS 4.5,Tommy,4.1VS 4.3,David,7-Feb
18,2018-02-07,9:45,1.5 VS 1.4,Julian,2.6 VS 2.2,Jenny,3.2 VS 3.1,Mike,7-Feb
19,2018-02-07,NaN,BYE: 1.6,NaN,BYE: 2.1,NaN,BYE: 3.7,NaN,7-Feb
20,2018-02-14,6:45,NaN,NaN,NaN,NaN,NaN,NaN,14-Feb
21,2018-02-14,7:45,NaN,NaN,NaN,NaN,NaN,NaN,14-Feb
22,2018-02-14,8:45,NaN,NaN,NaN,NaN,NaN,NaN,14-Feb
23,2018-02-14,9:45,NaN,NaN,NaN,NaN,NaN,NaN,14-Feb
24,2018-02-14,NaN,BYE: 1.4,NaN,BYE: 2.2,NaN,BYE: 3.5,NaN,14-Feb
25,2018-02-21,6:45,NaN,NaN,NaN,NaN,NaN,NaN,21-Feb
26,2018-02-21,7:45,NaN,NaN,NaN,NaN,NaN,NaN,21-Feb
27,2018-02-21,8:45,NaN,NaN,NaN,NaN,NaN,NaN,21-Feb
28,2018-02-21,9:45,NaN,NaN,NaN,NaN,NaN,NaN,21-Feb
29,2018-02-21,NaN,BYE: 1.3,NaN,BYE: 2.5,NaN,BYE: 3.6,NaN,21-Feb
30,2018-02-28,6:45,NaN,NaN,NaN,NaN,NaN,NaN,28-Feb
31,2018-02-28,7:45,NaN,NaN,NaN,NaN,NaN,NaN,28-Feb
32,2018-02-28,8:45,NaN,NaN,NaN,NaN,NaN,NaN,28-Feb
33,2018-02-28,9:45,NaN,NaN,NaN,NaN,NaN,NaN,28-Feb
34,2018-02-28,NaN,BYE: 1.7,NaN,BYE: 2.7,NaN,BYE: 3.2,NaN,28-Feb
35,2018-03-07,NaN,TBA,NaN,TBA,NaN,TBA,NaN,7-Mar
36,NaT,NaN,TBA,NaN,TBA,NaN,TBA,NaN,SEMI
37,NaT,NaN,TBA,NaN,TBA,NaN,TBA,NaN,FINALS
38,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FINALS
39,2018-03-14,NaN,TBA,NaN,TBA,NaN,TBA,NaN,14-Mar
40,NaT,NaN,TBA,NaN,TBA,NaN,TBA,NaN,GRAND
41,NaT,NaN,TBA,NaN,TBA,NaN,TBA,NaN,FINALS
42,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FINALS
43,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FINALS

In [221]:
def game_time(team):
    # todays date
    today = date.today()
    cutoff = today + timedelta(days=6.5)
    
    df2.Date = pd.to_datetime(df2.Date,format='%d-%b-%Y',errors='coerce')
    mask = (df2['Date'] > today) & (df2['Date'] <= (today+timedelta(days=6.5)))
    mask2 = (df2['court1'].str.contains(team) | df2['court2'].str.contains(team) | df2['court3'].str.contains(team))
    return df2[mask & mask2]['Time']

In [222]:
game_time('2.4')

15    6:45
Name: Time, dtype: object

In [220]:
df2[mask & mask2]['Time']

15    6:45
Name: Time, dtype: object

In [223]:
df2[mask & mask2]['Date'].astype(str)

15    2018-02-07
Name: Date, dtype: object

In [26]:
msg = ("Your game is at: " + df2[mask & mask2]['Time'].values[0] + " on " + df2[mask & mask2]['Date1'].values[0] + ". Team-" + team)

In [27]:
msg

u'Your game is at: 8:45 on 9-Aug. Team-3.7'

In [28]:
type(msg)

unicode

In [29]:
team = '3.7'
mask = (df2['Date'] > today) & (df2['Date'] <= (today+timedelta(days=6.5)))
mask2 = (df2['court1'].str.contains(team) | df2['court2'].str.contains(team) | df2['court3'].str.contains(team))
msg = ("Your game is at: " + df2[mask & mask2]['Time'].values[0] + " on " + df2[mask & mask2]['Date1'].values[0] + ". Team-" + team)

In [ ]:
client.messages.create(
    to="Censored number",
    from_="Number",
    body="sdfsdfsdf" + " " +msg)

In [32]:
msg

u'Your game is at: 8:45 on 9-Aug. Team-3.7'

In [33]:
from twilio.rest import Client

In [34]:
# put your own credentials here
account_sid = "AC12cfe202884603688368f2d32213cdeb"
auth_token = "80a4ff494dcbca5a3b4a086893814608"

client = Client(account_sid, auth_token)

In [35]:
flying_pandas = {"name1":"+num1","name2":"+num2","name3":"+num3","name4":"num3"}

In [ ]:
for key, value in flying_pandas.iteritems():
    client.messages.create(
    to=value,
    from_="+61437794147",
    body=key + " " +msg)

In [40]:
client.messages.create(
    to="+61421042726",
    from_="+61437794147",
    body=msg)